# Generated by Django 4.2 on 2023-04-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_alter_cadastroaluno_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroaluno',
            name='datadenascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cadastroaluno',
            name='ra',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadastroaluno',
            name='rg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
