# Generated by Django 4.2 on 2023-04-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0010_delete_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('ra', models.CharField(max_length=100, null=True)),
                ('bimestre1_prova1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre1_prova2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre1_prova3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre2_prova1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre2_prova2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre2_prova3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre3_prova1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre3_prova2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre3_prova3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre4_prova1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre4_prova2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre4_prova3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre5_prova1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre5_prova2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre5_prova3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre6_prova1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre6_prova2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre6_prova3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
