# Generated by Django 4.2 on 2023-04-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0013_rename_nome_cadastroaluno_bairro_aluno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre1_prova1',
            new_name='nota',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre1_prova2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre1_prova3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre2_prova1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre2_prova2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre2_prova3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre3_prova1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre3_prova2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre3_prova3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre4_prova1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre4_prova2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre4_prova3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre5_prova1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre5_prova2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre5_prova3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre6_prova1',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre6_prova2',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre6_prova3',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='ra',
        ),
        migrations.AddField(
            model_name='notas',
            name='atividade',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='bimestre',
            field=models.IntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre'), (5, '5º Bimestre'), (6, '6º Bimestre')], null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='cpf_aluno',
            field=models.CharField(default=1, max_length=11, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
