# Generated by Django 4.2 on 2023-04-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0014_rename_bimestre1_prova1_notas_nota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faltas',
            name='bimestre1_faltas',
        ),
        migrations.RemoveField(
            model_name='faltas',
            name='bimestre2_faltas',
        ),
        migrations.RemoveField(
            model_name='faltas',
            name='bimestre3_faltas',
        ),
        migrations.RemoveField(
            model_name='faltas',
            name='bimestre4_faltas',
        ),
        migrations.RemoveField(
            model_name='faltas',
            name='bimestre5_faltas',
        ),
        migrations.RemoveField(
            model_name='faltas',
            name='bimestre6_faltas',
        ),
        migrations.RemoveField(
            model_name='faltas',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='faltas',
            name='ra',
        ),
        migrations.AddField(
            model_name='faltas',
            name='cpf_aluno',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='faltas',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='faltas',
            name='presenca',
            field=models.CharField(choices=[(1, 'Presente'), (2, 'Ausente')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='faltas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
