# Generated by Django 4.2 on 2023-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0016_rename_cpf_aluno_faltas_cpf_faltas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='id_notas',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastroaluno',
            name='cpf_aluno',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notas',
            name='cpf_notas',
            field=models.CharField(max_length=11),
        ),
    ]
