# Generated by Django 4.2 on 2023-04-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0017_notas_id_notas_alter_cadastroaluno_cpf_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='id_notas',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
