# Generated by Django 4.2 on 2023-04-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0018_alter_notas_id_notas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faltas',
            old_name='data',
            new_name='data_faltas',
        ),
        migrations.RenameField(
            model_name='faltas',
            old_name='presenca',
            new_name='presenca_faltas',
        ),
        migrations.RemoveField(
            model_name='faltas',
            name='id',
        ),
        migrations.AddField(
            model_name='faltas',
            name='id_faltas',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faltas',
            name='cpf_faltas',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
