# Generated by Django 4.2 on 2023-04-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0020_cadastroaluno_id_aluno_alter_cadastroaluno_cpf_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroaluno',
            name='classe',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
