# Generated by Django 4.2 on 2023-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0024_cadastroaluno_professor_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faltas',
            old_name='data_faltas',
            new_name='datahoje_falta',
        ),
        migrations.RenameField(
            model_name='faltas',
            old_name='id_faltas',
            new_name='id_falta',
        ),
        migrations.RenameField(
            model_name='faltas',
            old_name='cpf_faltas',
            new_name='nomecompleto_aluno',
        ),
        migrations.RenameField(
            model_name='faltas',
            old_name='presenca_faltas',
            new_name='presenca_falta',
        ),
        migrations.AddField(
            model_name='faltas',
            name='turma_aluno',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
