# Generated by Django 4.2 on 2023-04-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0025_rename_data_faltas_faltas_datahoje_falta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltas',
            name='presenca_falta',
            field=models.CharField(choices=[(1, 'F'), (2, 'P')], max_length=10, null=True),
        ),
    ]
