# Generated by Django 4.2 on 2023-04-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0028_faltas_aluno_alter_faltas_nomecompleto_falta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faltas',
            old_name='aluno',
            new_name='FK_Cad_Fal',
        ),
    ]
