# Generated by Django 4.2 on 2023-04-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0029_rename_aluno_faltas_fk_cad_fal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faltas',
            old_name='turma_falta',
            new_name='classe_falta',
        ),
        migrations.RemoveField(
            model_name='faltas',
            name='FK_Cad_Fal',
        ),
    ]
