# Generated by Django 4.2 on 2023-04-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0030_rename_turma_falta_faltas_classe_falta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='atividade',
            new_name='atividade_nota',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='cpf_notas',
            new_name='classe_nota',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='nota',
            new_name='nota_nota',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='bimestre',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='id_notas',
        ),
        migrations.AddField(
            model_name='notas',
            name='datahoje_nota',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notas',
            name='id_nota',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notas',
            name='nomecompleto_nota',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
