# Generated by Django 4.2 on 2023-05-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0031_rename_atividade_notas_atividade_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='datahoje_nota',
            field=models.DateField(max_length=10),
        ),
    ]
