# Generated by Django 4.2 on 2023-04-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastroaluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('datadenascimento', models.DateField()),
                ('ra', models.CharField(max_length=10)),
                ('rg', models.CharField(max_length=20)),
            ],
        ),
    ]
