# Generated by Django 4.2 on 2023-04-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroaluno',
            name='ra',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastroaluno',
            name='rg',
            field=models.CharField(max_length=100),
        ),
    ]
