# Generated by Django 4.2 on 2023-04-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_cadastroaluno_ra_alter_cadastroaluno_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroaluno',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
