# Generated by Django 4.2 on 2023-04-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_alter_cadastroaluno_datadenascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('bimestre_1_materia_1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_1_materia_2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_1_materia_3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_2_materia_1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_2_materia_2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_2_materia_3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_3_materia_1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_3_materia_2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_3_materia_3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_4_materia_1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_4_materia_2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_4_materia_3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_5_materia_1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_5_materia_2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_5_materia_3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_6_materia_1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_6_materia_2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bimestre_6_materia_3', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'notas',
            },
        ),
    ]
