# Generated by Django 4.2 on 2023-04-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_notas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_1_materia_1',
            new_name='bimestre1_prova1',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_1_materia_2',
            new_name='bimestre1_prova2',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_1_materia_3',
            new_name='bimestre1_prova3',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_2_materia_1',
            new_name='bimestre2_prova1',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_2_materia_2',
            new_name='bimestre2_prova2',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_2_materia_3',
            new_name='bimestre2_prova3',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_3_materia_1',
            new_name='bimestre3_prova1',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_3_materia_2',
            new_name='bimestre3_prova2',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_3_materia_3',
            new_name='bimestre3_prova3',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_4_materia_1',
            new_name='bimestre4_prova1',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_4_materia_2',
            new_name='bimestre4_prova2',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_4_materia_3',
            new_name='bimestre4_prova3',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_5_materia_1',
            new_name='bimestre5_prova1',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_5_materia_2',
            new_name='bimestre5_prova2',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_5_materia_3',
            new_name='bimestre5_prova3',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_6_materia_1',
            new_name='bimestre6_prova1',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_6_materia_2',
            new_name='bimestre6_prova2',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='bimestre_6_materia_3',
            new_name='bimestre6_prova3',
        ),
    ]
