# Generated by Django 4.2 on 2023-04-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_rename_bimestre_1_materia_1_notas_bimestre1_prova1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='ra',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
