from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    pagina_inicial, cadastro_professor, register_professor, turmasprofessor_json,
    listagem_turma_professor, selecionar_turma, registro, sobre, listagem_turmas,
    cadastro_turma, cadastro_aluno, cadastro_falta, area_secretaria,
    listagem_faltas, listagem_alunos, area_professor, area_aluno, listagem_notas,
    cadastro_nota, cadastrar_professores, atualizar_lista_notas, salvar_notas,
    salvar_presenca, associar_aluno, atualizar_lista, turmas_json, cadastrar_notas,
    cadastrar_faltas, cadastrar_alunos, excluir_aluno, excluir_falta, excluir_nota,
    faltas_json, alunos_json, notas_json
)

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='paginas/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('registro/', registro, name='registro'),
    path('index/', pagina_inicial, name='index'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('sobre/', sobre, name='sobre'),
    path('areadoprofessor/', area_professor, name='areadoprofessor'),
    path('areadoaluno/', area_aluno, name='areadoaluno'),
    path('areadasecretaria/', area_secretaria, name='areadasecretaria'),
    path('cadastroaluno/', cadastro_aluno, name='cadastroaluno'),
    path('cadastroprofessor/', cadastro_professor, name='cadastroprofessor'),
    path('cadastrofalta/', cadastro_falta, name='cadastrofalta'),
    path('cadastronota/', cadastro_nota, name='cadastronota'),
    path('cadastroturma/', cadastro_turma, name='cadastroturma'),
    path('listagemalunos/', listagem_alunos, name='listagemalunos'),
    path('listagemnotas/', listagem_notas, name='listagemnotas'),
    path('listagemfaltas/', listagem_faltas, name='listagemfaltas'),
    path('listagemturmas/', listagem_turmas, name='listagemturmas'),
    path('listagemturmaprofessor/', listagem_turma_professor, name='listagemturmaprofessor'),
    path('turmas_json/', turmas_json, name='turmas_json'),
    path('notas_json/', notas_json, name='notas_json'),
    path('faltas_json/', faltas_json, name='faltas_json'),
    path('alunos_json/', alunos_json, name='alunos_json'),
    path('cadastrar_notas/', cadastrar_notas, name='cadastrar_notas'),
    path('cadastrar_faltas/', cadastrar_faltas, name='cadastrar_faltas'),
    path('cadastrar_alunos/', cadastrar_alunos, name='cadastrar_alunos'),
    path('excluir_aluno/<int:id_aluno>/', excluir_aluno, name='excluir_aluno'),
    path('excluir_nota/<int:id_notas>/', excluir_nota, name='excluir_nota'),
    path('excluir_falta/<int:id_faltas>/', excluir_falta, name='excluir_falta'),
    path('associar_aluno/<int:id_aluno>/', associar_aluno, name='associar_aluno'),
    path('atualizar_lista/', atualizar_lista, name='atualizar_lista'),
    path('salvar_presenca/', salvar_presenca, name='salvar_presenca'),
    path('atualizar_lista_notas/', atualizar_lista_notas, name='atualizar_lista_notas'),
    path('salvar_notas/', salvar_notas, name='salvar_notas'),
    path('cadastrar_professores/', cadastrar_professores, name='cadastrar_professores'),
    path('selecionar_turma/<int:id_professor>/', selecionar_turma, name='selecionar_turma'),
    path('turmasprofessor_json/', turmasprofessor_json, name='turmasprofessor_json'),
    path('register/', register_professor, name='register_professor'),
]
